### ISSUE TITLE
Discussion: How to handle PyPI packages?

### ISSUE THREAD

**Issue by samueljohn** [Homebrew/homebrew-python#109]
The `depends_on "nose" => :python` or `depends_on "nose" => :python3` will be [deprecated](https://github.com/Homebrew/homebrew/issues/27326).

So we have to resort to download the package via `resource` and install it later on.
This has been currently implemented in `numpy` and `scipy`.

#### A few questions arise, and I want to discuss them here:

- Do we force our (possibly) outdated resource version if a python package is already installed?
- How does upgrading work if at all? Can the user `pip install nose --upgrade`?
- Do we install to the `prefix` of the formula (and let homebrew symlink) it to the global `brew --prefix`?
- We need, in general, support system python from OS X, too.
- Does `brew link/unlink` work.
- Shall we just download and put stuff in `postinstall` (as done in `python.rb` to support bottles in the future)?
- If we `brew rm <formula>` how do we clean up? At all? Shall we? How to handle the `.pyc` files, which can still be imported by python, even though the `py` files are missing.

**Comment by tdsmith** [comment]
I think the policy questions here have been resolved; future discussion should take the form of a PR against https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Python-for-Formula-Authors.md.
