### ISSUE TITLE
vpython: handle deps

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-python#155]
Soft in the sense that it builds without them and features go missing at runtime:
* [Polygon2](https://pypi.python.org/pypi/Polygon2) and caveats that Polygon2 is "free" only for non-commercial use
* [FontTools](https://pypi.python.org/pypi/FontTools)
* [ttfquery](https://pypi.python.org/pypi/TTFQuery/1.0.5)

Holding off on this pending a decision wrt boost-python in core.

**Comment by jbattat** [comment]
Any resolution to this problem (vpython only updating during mouse motion)?  I'm seeing the same issue on my system.

I'm using brewed python
```
$ which python
/usr/local/bin/python
```

I tried reinstalling wxpython
`$ brew reinstall wxpython --build-from-source`
but the problem persists.

sspickle suggested pointing to a binary wxPython install
```
 If I manually point to the old wxPython install (binary from wxpython.org) it works as expected
```
How do you do that?

**Comment by sspickle** [comment]
There’s a way to tell home-brew to use an older version. You want wxpython 3.0.0.0.

I’ll try to track down the instructions when I can later today. 

-steve

**Comment by tdsmith** [comment]
If you've isolated this to a difference between wxpython 3.0.0.0 and a later version, which I don't think we had conclusively determined before, it would be great if you could link to a ticket filed against either vpython or wxpython describing the behavior.

**Comment by tdsmith** [comment]
PyPI dependencies of vpython are now installed with vpython so I've closed this ticket. Discussion of the mouse issue can happen in a new issue if you'd like me to track it. Thanks!

**Comment by sspickle** [comment]
I’d love to help with that, but I’m not sure how to best handle it. I’ve already reported the trouble on the wxPython mailing list, but I haven’t submitted a formal ticket. Where does a ticket really belong? It’ s not clear that it’s a home-brew problem.

BTW I’ve had some luck with:

brew switch wxpython 3.0.0.0

It works on one machine, but not on another. There is conflicting advice online about how to pin a home-brew version. Some folks say use 

‘brew versions’

and suchlike, but I get:

aluminum:~ steve$ brew versions
Error: Unknown command: versions

So I guess that’s old advice?

Anyway, try the ‘switch’ command and see if that works for you.

thanks!
-steve
