### ISSUE TITLE
ooniprobe Formula is out of date and could be implemented differently

### ISSUE THREAD

**Issue by hellais** [Homebrew/homebrew-python#177]
Hi I wanted to suggest updating the formula for ooniprobe and perhaps changing it to use a pattern similar to [this formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/jrnl.rb) so that it also installs the python packages it depends on from pypi.

Also, is there a reason why this formula cannot be part of the main homebrew instead of this tap?

This is the related tor trac ticket we have open on the matter: https://trac.torproject.org/projects/tor/ticket/7389#comment:5

**Comment by tdsmith** [comment]
I'm removing the ooni-probe formula from this repo since it's out of date, uses old syntax, and should live in the main repo. `mkpydeps` has been supplanted by `homebrew-pypi-poet`: https://github.com/tdsmith/homebrew-pypi-poet
