### ISSUE TITLE
Multiple python versions support

### ISSUE THREAD

**Issue by joaoponceleao** [Homebrew/homebrew-python#188]
Hi,
I currently use pyenv (https://github.com/yyuu/pyenv) to manage different python versions.
I understand the homebrew-python will install to whichever python is first on the PATH. Is it possible to use this with multiple versions (whether managed by pyenv or not)? If so, how? Do I simply activate each python version (i.e. put it at the front of the path) and run `brew install numpy` or `brew link bumpy` again?
Thanks for the help.

**Comment by tdsmith** [comment]
This is unsupported, sorry. Just using `pip install numpy scipy` is probably a better solution for you.
