### ISSUE TITLE
Pillow fails to build

### ISSUE THREAD

**Issue by captivus** [Homebrew/homebrew-python#190]
I'm trying to install pillow after having uninstalled it in hopes to resolve this same issue. Please see output from the failed build below:

==> Installing pillow from homebrew/homebrew-python
==> Downloading https://github.com/python-pillow/Pillow/archive/2.7.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/pillow-2.7.0.tar.gz
==> Patching
==> python setup.py build_ext --disable-jpeg2000
Building using 4 processes
clang -bundle -undefined dynamic_lookup -L/usr/local/lib -L/usr/local/opt/sqlite/lib build/temp.macosx-10.10-x86_64-2.7/_imagingtk.o build/temp.macosx-10.10-x86_64-2.7/Tk/tkImaging.o -L/usr/local/Cellar/jpeg/8d/lib -L/usr/local/Cellar/libtiff/4.0.3/lib -L/usr/local/Cellar/freetype/2.5.5/lib -L/usr/local/Cellar/little-cms2/2.6/lib -L/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib -L/opt/X11/lib -L/usr/local/lib -L/usr/lib -o build/lib.macosx-10.10-x86_64-2.7/PIL/_imagingtk.so -framework Tcl -framework Tk
clang: error: no such file or directory: 'build/temp.macosx-10.10-x86_64-2.7/_imagingtk.o'
clang: error: no such file or directory: 'build/temp.macosx-10.10-x86_64-2.7/Tk/tkImaging.o'
error: command 'clang' failed with exit status 1

I am running Xcode 6.1.1 and CLT 6.1.1.  The gist is here:  https://gist.github.com/anonymous/51dbcbb3f27fb9c886d2.  I appreciate your help.

**Comment by tdsmith** [comment]
Did you install python using `--with-brewed-tk`? `-I/System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers -I/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers` is missing from the clang invocation and I'm not sure why.

**Comment by captivus** [comment]
I did not install python using that argument.

**Comment by tdsmith** [comment]
Is there a chance you've installed the Xcode command line tools since installing Python? How did you install Python? Does `brew reinstall python` resolve this?

**Comment by captivus** [comment]
The CLT have been upgraded several times since installing Python.  Reinstalling Python did not resolve.

**Comment by ChristianSch** [comment]
I ran into the very same problem. I've installed Xcode6 and the new beta. Any way to resolve this?

By the way:
```
~> ls /System/Library/Frameworks/Tcl.framework/Versions/8.5
Resources      Tcl            _CodeSignature tclsh8.5
```
There is no `Headers` dir.

**Comment by tdsmith** [comment]
@ChristianSch, installing the Xcode Command-Line Tools with `xcode-select --install` should help in your case.

**Comment by tdsmith** [comment]
I'm 90% sure the problem was that you had Tcl and Tk frameworks in /Library missing the magic system X11 headers. Committed a fix. Sorry for the delay!

**Comment by ChristianSch** [comment]
@tdsmith It works now. Thank you very much!

**Comment by captivus** [comment]
This works now.  Thank you!

**Comment by luchuan** [comment]
:+1:
