### ISSUE TITLE
python setup.py build --fcompiler=gnu95 install failed

### ISSUE THREAD

**Issue by dendisuhubdy** [Homebrew/homebrew-python#198]
dendisuhubdy:~ dendisuhubdy$ brew upgrade
==> Upgrading 1 outdated package, with result:
opencv 2.4.10.1
==> Upgrading opencv
==> Installing opencv dependency: homebrew/python/numpy
==> Downloading https://downloads.sourceforge.net/project/numpy/NumPy/1.9.1/numpy-1.9.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/numpy-1.9.1.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/nose/nose-1.3.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/numpy--nose-1.3.4.tar.gz
Warning: Language::Python.setup_install is deprecated.
If you are a formula author, please use
  system "python", *Language::Python.setup_install_args(prefix)
instead.
[..]
==> python setup.py build --fcompiler=gnu95 install --prefix=/usr/local/Cellar/numpy/1.9.1
  File "/private/tmp/numpy-4cmRt4/numpy-1.9.1/numpy/distutils/fcompiler/__init__.py", line 464, in customize
    self.find_executables()
  File "/private/tmp/numpy-4cmRt4/numpy-1.9.1/numpy/distutils/fcompiler/__init__.py", line 354, in find_executables
    raise CompilerNotFound('%s: f90 nor f77' % ctype)
numpy.distutils.fcompiler.CompilerNotFound: gnu95: f90 nor f77

**Comment by tdsmith** [comment]
Which fortran compiler are you trying to use and how did you install it?

**Comment by dendisuhubdy** [comment]
I used brew to install it, don't you use the GNU Fortran compiler?

Dendi Suhubdy
Fulbright Scholar
Candidate in Masters of Science in Financial Mathematics
NC State University

"The history of the progress of human liberty shows that all concessions yet
made have been born in struggle...if there is no struggle there is no
progress.
Those who profess to favor Freedom and yet depreciate agitation are [those]
who want crops without plowing up the ground....Power concedes nothing
without
demand. It never did and it never will."

-Frederick Douglass

**Comment by tdsmith** [comment]
What's `which gfortran` and `gfortran -v`? Do you have the `FC` environment variable set?

**Comment by dendisuhubdy** [comment]
dendisuhubdy:socket dendisuhubdy$ gfortran -v

-bash: gfortran: command not found


I haven't even installed gfortran. I just updated brew.

Dendi Suhubdy
Fulbright Scholar
Candidate in Masters of Science in Financial Mathematics
NC State University

"The history of the progress of human liberty shows that all concessions yet
made have been born in struggle...if there is no struggle there is no
progress.
Those who profess to favor Freedom and yet depreciate agitation are [those]
who want crops without plowing up the ground....Power concedes nothing
without
demand. It never did and it never will."

-Frederick Douglass

**Comment by dendisuhubdy** [comment]
dendisuhubdy:socket dendisuhubdy$ brew install gfortran

Error: No available formula for gfortran

GNU Fortran is now provided as part of GCC, and can be installed with:

  brew install gcc

dendisuhubdy:socket dendisuhubdy$ gcc -v

Configured with: --prefix=/Library/Developer/CommandLineTools/usr
--with-gxx-include-dir=/usr/include/c++/4.2.1

Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)

Target: x86_64-apple-darwin14.0.0

Dendi Suhubdy
Fulbright Scholar
Candidate in Masters of Science in Financial Mathematics
NC State University

"The history of the progress of human liberty shows that all concessions yet
made have been born in struggle...if there is no struggle there is no
progress.
Those who profess to favor Freedom and yet depreciate agitation are [those]
who want crops without plowing up the ground....Power concedes nothing
without
demand. It never did and it never will."

-Frederick Douglass

**Comment by tdsmith** [comment]
That gcc is not the same gcc; Homebrew's gcc formula doesn't install a `gcc` binary. It's a problem that you don't have a `gfortran` in your path, though. `brew reinstall gcc`, please.

**Comment by dendisuhubdy** [comment]
Thank you that helped! It resolved the problem!

Dendi Suhubdy
Fulbright Scholar
Candidate in Masters of Science in Financial Mathematics
NC State University

"The history of the progress of human liberty shows that all concessions yet
made have been born in struggle...if there is no struggle there is no
progress.
Those who profess to favor Freedom and yet depreciate agitation are [those]
who want crops without plowing up the ground....Power concedes nothing
without
demand. It never did and it never will."

-Frederick Douglass
