### ISSUE TITLE
Pillow failed to build on Mac Yosemite 10.10.2

### ISSUE THREAD

**Issue by noctuelle** [Homebrew/homebrew-python#200]
Hello,

   I had a problem installing pillow, which I need to install basemap.
Here is the url generated with brew gist-logs.

With best regards,
noctu

https://gist.github.com/548091cdde03a3c6eda0

**Comment by tdsmith** [comment]
The libraries Anaconda ships are conflicting with Homebrew's libraries. We can't support Anaconda, sorry.
