### ISSUE TITLE
Support for sim-x

### ISSUE THREAD

**Issue by webdrone** [Homebrew/homebrew-python#201]
Any chance of supporting this?
http://simx.lanl.gov

If there is a better alternative someone is aware of, I'd appreciate the head's up.

**Comment by tdsmith** [comment]
I'd be happy to review a pull request! We have [a guide for creating formulas](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md), some [Python-specific help](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Python-for-Formula-Authors.md), and [a guide to help you with opening a PR](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md). Let me know if I can help with anything!
