### ISSUE TITLE
Pyfontaine install error

### ISSUE THREAD

**Issue by EbenSorkin** [Homebrew/homebrew-python#202]
@davelab6 

I have several problems with parts needed to run Pyfontaine but I don't know how to resolve them. 

The first two come from running commands that are not visible from the "How to" part of the Pyfontaine Git hub pages but come in the Readme. The last one comes up with the basic installation process.

I was running this command

**Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ brew install samueljohn/python/numpy**

One occurs with the setup of Numpy - see the final line below

**==> python setup.py build --fcompiler=gnu95 install --prefix=/usr/local/Cellar/n
  File "/private/tmp/numpy-TVCWSr/numpy-1.9.1/numpy/distutils/command/build_ext.py", line 18, in <module>
    from numpy.distutils.system_info import combine_paths
  File "/private/tmp/numpy-TVCWSr/numpy-1.9.1/numpy/distutils/system_info.py", line 235, in <module>
    triplet = str(p.communicate()[0].decode().strip())
LookupError: no codec search functions registered: can't find encoding**

Another is with Nose

**File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 16, in <module>
    import encodings.aliases
ImportError: No module named aliases**

When I try to run install Pyfontaine it also mentions the aliases problem

**File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 16, in <module>
    import encodings.aliases
ImportError: No module named aliases
Sorkin-Type-Co-Mac-Book-Pro-3:pyfontaine ebensorkin$ **

*Any suggestion much appreciated.*

**Comment by davelab6** [comment]
Vitaly, do you have any tips? :)

**Comment by davelab6** [comment]
@vitalyvolkhov

**Comment by tdsmith** [comment]
There appears to be something quite wrong with your python installation! Can you share the outputs of `brew doctor`, `brew config`, `which python`, `python -c "import sys; print sys.version; print sys.path"`, and `brew gist-logs numpy`?

**Comment by EbenSorkin** [comment]
Thanks very much!

Here are the results

-=-=-=-=-=-=-=-=-=-=

brew doctor:


Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.


Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run `brew update`.
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ 
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ brew update
Updated Homebrew from 76680d54 to 8c393d3e.
==> New Formulae
launchdns	lfe		peco		riemann-client
==> Updated Formulae
apache-spark	cmake		percona-server	python3
artifactory	iojs		py2cairo	sip
clang-format	libvisio	python		tth
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ 

-=-=-=-=-=-=-=-=-=-=

Brew Config:

Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 8c393d3ea2589117f8f419b18187f12fe94f2dcc
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.9.5-x86_64
Xcode: 6.1.1
CLT: 6.0.0.0.1.1410400753
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.6.0_65
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ 

-=-=-=-=-=-=-=-=-=-=

which Python:

Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ which python
/usr/local/bin/python
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$

-=-=-=-=-=-=-=-=-=-=

python -c "import sys; print sys.version; print sys.path” :


Last login: Wed Feb 11 00:32:22 on ttys000
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ python -c "import sys; print sys.version; print sys.path"
2.7.9 (default, Jan 29 2015, 06:28:58) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
['', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg', '/Library/Python/2.7/site-packages/requests-2.3.0-py2.7.egg', '/Library/Python/2.7/site-packages/FontTools', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontaine-1.3.0-py2.7.egg', '/Library/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/fontaine-1.1.3-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg', '/usr/local/lib/python2.7/site-packages/fontaine-1.3.0-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0', '/Library/Python/2.7/site-packages', '/Users/ebensorkin/code/DialogKit/Lib', '/Users/ebensorkin/code/RoboFab/Lib', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/gtk-2.0']
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ 

-=-=-=-=-=-=-=-=-=-=

python -c "import sys; print sys.version; print sys.path” :

Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ python -c "import sys; print sys.version; print sys.path"
2.7.9 (default, Jan 29 2015, 06:28:58) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
['', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg', '/Library/Python/2.7/site-packages/requests-2.3.0-py2.7.egg', '/Library/Python/2.7/site-packages/FontTools', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontaine-1.3.0-py2.7.egg', '/Library/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/fontaine-1.1.3-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg', '/usr/local/lib/python2.7/site-packages/fontaine-1.3.0-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0', '/Library/Python/2.7/site-packages', '/Users/ebensorkin/code/DialogKit/Lib', '/Users/ebensorkin/code/RoboFab/Lib', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/gtk-2.0']

-=-=-=-=-=-=-=-=-=-=

brew gist-logs numpy :

Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ brew gist-logs numpy
https://gist.github.com/837f18664b78f490c524
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$

-=-=-=-=-=-=-=-=-=-=

This may be overkill or an excess of caution but I downloaded the contents of the gist logs in case it wasn’t going to be available to you and attached it here.



Again, thanks!

-e.

**Comment by EbenSorkin** [comment]
@davelab6

brew doctor:


Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.


Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run `brew update`.
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ 
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ brew update
Updated Homebrew from 76680d54 to 8c393d3e.
==> New Formulae
launchdns	lfe		peco		riemann-client
==> Updated Formulae
apache-spark	cmake		percona-server	python3
artifactory	iojs		py2cairo	sip
clang-format	libvisio	python		tth
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ 

-=-=-=-=-=-=-=-=-=-=

Brew Config:

Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 8c393d3ea2589117f8f419b18187f12fe94f2dcc
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.9.5-x86_64
Xcode: 6.1.1
CLT: 6.0.0.0.1.1410400753
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.6.0_65
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ 

-=-=-=-=-=-=-=-=-=-=

which Python:

Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ which python
/usr/local/bin/python
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$

-=-=-=-=-=-=-=-=-=-=

python -c "import sys; print sys.version; print sys.path” :


Last login: Wed Feb 11 00:32:22 on ttys000
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ python -c "import sys; print sys.version; print sys.path"
2.7.9 (default, Jan 29 2015, 06:28:58) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
['', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg', '/Library/Python/2.7/site-packages/requests-2.3.0-py2.7.egg', '/Library/Python/2.7/site-packages/FontTools', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontaine-1.3.0-py2.7.egg', '/Library/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/fontaine-1.1.3-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg', '/usr/local/lib/python2.7/site-packages/fontaine-1.3.0-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0', '/Library/Python/2.7/site-packages', '/Users/ebensorkin/code/DialogKit/Lib', '/Users/ebensorkin/code/RoboFab/Lib', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/gtk-2.0']
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ 

-=-=-=-=-=-=-=-=-=-=

python -c "import sys; print sys.version; print sys.path” :

Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ python -c "import sys; print sys.version; print sys.path"
2.7.9 (default, Jan 29 2015, 06:28:58) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
['', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg', '/Library/Python/2.7/site-packages/requests-2.3.0-py2.7.egg', '/Library/Python/2.7/site-packages/FontTools', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontaine-1.3.0-py2.7.egg', '/Library/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/fontaine-1.1.3-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg', '/usr/local/lib/python2.7/site-packages/fontaine-1.3.0-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0', '/Library/Python/2.7/site-packages', '/Users/ebensorkin/code/DialogKit/Lib', '/Users/ebensorkin/code/RoboFab/Lib', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/gtk-2.0']

-=-=-=-=-=-=-=-=-=-=

brew gist-logs numpy :

Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$ brew gist-logs numpy
https://gist.github.com/837f18664b78f490c524
Sorkin-Type-Co-Mac-Book-Pro-3:~ ebensorkin$

-=-=-=-=-=-=-=-=-=-=

**Comment by davelab6** [comment]
@vitalyvolkhov any tips?
