### ISSUE TITLE
PIL and Pillow

### ISSUE THREAD

**Issue by HughP** [Homebrew/homebrew-python#204]
Is there a way to use PIL? I understand that Pillow has replaced PIL in homebrew (and is in general more up to date). However, I want to use a module, basemap, which works with matplotlib. However, some of the graphics rendering fail, saying they require PIL. I'm just wondering if there is a way to brew the latest version of PIL from another repo, kinda like an older version of a utility or something.

**Comment by tdsmith** [comment]
There is no way to install old-school PIL with Homebrew, sorry. Are you sure it doesn't work with pillow? I'd complain at the basemap people.
