### ISSUE TITLE
scipy installation fortran problem

### ISSUE THREAD

**Issue by ajkal** [Homebrew/homebrew-python#205]
After doing some digging I seem to be having a similar problem to what others have experienced in trying to install scipy via homebrew on OS X 10.9. It doesn't look exactly the same though which is why I've submitted a new issue. I'm not an expert on package managers so I can't say for sure but it seems to have something to do with the fact that gfortran is now installed in combo with gcc and as such gfortran is not visible to brew. For now I've chosen to just install scipy with pip but if there is a solution to this issue please let me know. Thanks!

/Users/ajkal$ brew install scipy --with-openblas
==> Installing scipy from samueljohn/homebrew-python
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Building with an alternative Fortran compiler
This is unsupported.
Warning: No Fortran optimization information was provided.  You may want to consider
setting FCFLAGS and FFLAGS or pass the `--default-fortran-flags` option to
`brew install` if your compiler is compatible with GCC.

If you like the default optimization level of your compiler, ignore this
warning.
==> Building with an alternative Fortran compiler
This is unsupported.
Warning: No Fortran optimization information was provided.  You may want to consider
setting FCFLAGS and FFLAGS or pass the `--default-fortran-flags` option to
`brew install` if your compiler is compatible with GCC.

If you like the default optimization level of your compiler, ignore this
warning.
==> Downloading https://downloads.sourceforge.net/project/scipy/scipy/0.15.1/scipy-0.15.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/scipy-0.15.1.tar.gz
==> python setup.py build --fcompiler=gnu95
  Referenced from: /usr/local/Cellar/gcc/4.9.2_1/libexec/gcc/x86_64-apple-darwin13.4.0/4.9.2/f951
  Reason: image not found
gfortran: internal compiler error: Trace/BPT trap: 5 (program f951)
sh: line 1:  7536 Abort trap: 6           /usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops -I/usr/local/lib/python2.7/site-packages/numpy/core/include -c -c scipy/fftpack/src/dfftpack/dcosqb.f -o build/temp.macosx-10.9-x86_64-2.7/scipy/fftpack/src/dfftpack/dcosqb.o
error: Command "/usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops -I/usr/local/lib/python2.7/site-packages/numpy/core/include -c -c scipy/fftpack/src/dfftpack/dcosqb.f -o build/temp.macosx-10.9-x86_64-2.7/scipy/fftpack/src/dfftpack/dcosqb.o" failed with exit status 134

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/samueljohn/homebrew-python/issues

**Comment by tdsmith** [comment]
Installing scipy with pip isn't a bad idea if you don't want to build against openblas. This looks actually less complicated than the other issues; `brew reinstall $(brew deps gcc)` will probably get you back up and running. If it doesn't, the output of `brew gist-logs scipy` would be informative!
