### ISSUE TITLE
matplotlib and numpy have new versions

### ISSUE THREAD

**Issue by basnijholt** [Homebrew/homebrew-python#206]
matplotlib (Current: 1.4.2 Latest: 1.4.3)

numpy (Current: 1.9.1 Latest: 1.9.2)

**Comment by tdsmith** [comment]
Thanks for the report! I can spend some time on this later, but if you'd like to beat me to it, could you try and open a pull request? [This guide](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'll be happy to walk you through any questions you run in to, either here or on IRC.

**Comment by tdsmith** [comment]
Added numpy in #207; won't have a chance to work on matplotlib for a bit.

**Comment by basnijholt** [comment]
I've made a pull request for matplotlib. https://github.com/Homebrew/homebrew-python/pull/208
