### ISSUE TITLE
bottle all the things

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-python#214]
Does numpy really depend on `:python`? It probably doesn't!

**Comment by xu-cheng** [comment]
If we choose only to bottle against system python, I wonder how many people use NumPy in this way? If the majority of `homebrew-python` users use NumPy with brew python or even python3, we will offer a bottle which most of people won't use.

**Comment by tdsmith** [comment]
The question here is really: can we bottle against system python and deliver that bottle unmodified no matter which python will import it? I think we probably can, since `pip` delivers a binary wheel on OS X. We could probably even bottle for latest 3.x by default.

**Comment by xu-cheng** [comment]
> can we bottle against system python and deliver that bottle unmodified no matter which python will import it?

I think we can. NumPy which is built by brew python works fine under system python.
```
$ /usr/bin/python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys;  sys.path.insert(0, "/usr/local/opt/numpy/lib/python2.7/site-packages/")
>>> import numpy; print numpy.__file__
/usr/local/opt/numpy/lib/python2.7/site-packages/numpy/__init__.pyc
```

>  We could probably even bottle for latest 3.x by default. We can't, oops, but that's a limitation of our bottling process, probably.

Instead of doing these hard choices, is there any chance that we solve it systematically? Create new DSLs like `py_bottle` and `py3_bottle`? Changing the bottle process using [`hooks`](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/hooks/bottles.rb)?

**Comment by tdsmith** [comment]
The next challenge is to try to build scipy from source using a bottled numpy from the wrong python, since numpy has a special distutils that scipy uses, which is configured at numpy build time. If that works, I think we're set.

Right now, dependencies with a default formula always introduce a hard dependency on that formula for bottles. We could add a dependency tag that changes that behavior so that the dependency is evaluated at install time. I don't know what to call it; `:bottle_install`?

**Comment by xu-cheng** [comment]
> If that works, I think we're set.

It works.
```
$ /usr/bin/python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.insert(0, "/usr/local/opt/numpy/lib/python2.7/site-packages")
>>> sys.path.insert(0, "/usr/local/opt/numpy/libexec/nose/lib/python2.7/site-packages/")
>>> sys.path.insert(0, "/usr/local/opt/scipy-test/lib/python2.7/site-packages")
>>> import scipy
>>> scipy.test()
Running unit tests for scipy
NumPy version 1.9.2
NumPy is installed in /usr/local/opt/numpy/lib/python2.7/site-packages/numpy
SciPy version 0.15.1
SciPy is installed in /usr/local/opt/scipy-test/lib/python2.7/site-packages/scipy
Python version 2.7.6 (default, Sep  9 2014, 15:04:36) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
nose version 1.3.4

...

Ran 17003 tests in 110.960s

OK (KNOWNFAIL=96, SKIP=1200)
<nose.result.TextTestResult run=17003 errors=0 failures=0>
```

**Comment by tdsmith** [comment]
numpy bottled in 0a6cfed

**Comment by tdsmith** [comment]
scipy bottled in 7edce21

**Comment by xu-cheng** [comment]
It just comes to me. After the recent, how to explicitly build formulae against brew python? Should we add an option like "with-brew-python"?

**Comment by tdsmith** [comment]
There should be no need.

**Comment by tdsmith** [comment]
Why do you ask? Maybe I'm missing something.

**Comment by xu-cheng** [comment]
> There should be no need.

OK.

> Why do you ask? Maybe I'm missing something.

I was just thinking how to achieve the same behavior as before. Nothing dramatically. Although, I think we still need to add `depends_on :python if if MacOS.version <= :snow_leopard`.

**Comment by tdsmith** [comment]
That's a good point, about OS version.
