### ISSUE TITLE
numpy installation error OSX 10.10.3

### ISSUE THREAD

**Issue by falkuh** [Homebrew/homebrew-python#224]
OSX Yosemite 10.10.3 here. According to http://stackoverflow.com/questions/24615005/how-to-install-numpy-for-python-3-3-5-on-mac-osx-10-9 I did:
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
`brew install python3`
`brew tap Homebrew/python`
`brew install numpy --with-python3`

and get the error:
`==> python3 setup.py build --fcompiler=gnu95 install --prefix=/usr/local/Cellar/numpy/1.9.2`
  `File "numpy/core/setup.py", line 42, in check_types`
    `out = check_types(*a, **kw)`
  `File "numpy/core/setup.py", line 293, in check_types`
    `"Cannot compile 'Python.h'. Perhaps you need to "\`
`SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.`

Any help ?

**Comment by tdsmith** [comment]
Please take a look at the troubleshooting guide linked at the foot of the error message and paste the output of `brew gist-logs numpy` here.

**Comment by falkuh** [comment]
Many thanks for the quick reply.
brew gist-logs numpy gave:
https://gist.github.com/9b34572a6d328c76b4b6 <https://gist.github.com/9b34572a6d328c76b4b6>

**Comment by tdsmith** [comment]
Uh oh; I can reproduce this: https://gist.github.com/7889988776d3204fe240

**Comment by falkuh** [comment]
I might add that the pre-compiled Anaconda bundle (Python3, numpy, matplotlib,...) seems to work fine.

**Comment by tdsmith** [comment]
If you're using Anaconda, you shouldn't mix and match. This is a build problem related to a change we made to how Python learns about include directories that's interacting badly with numpy's distutils.

**Comment by falkuh** [comment]
I have installed Anaconda AFTER the problem described above just to see whether its a generic problem with Yosemite. The problem is exactly the same both before and after Anaconda installation. As far as I can see, Anaconda sits completely shielded in ~/anaconda. The only thing Anaconda does outside is append its path to .bash_profile. 
I would prefer homebrew because updates and installation of particular modules should be easier (?)

**Comment by tdsmith** [comment]
This should be fixed after a `brew update`; I'm applying a patch to `numpy.distutils` to work around this. Thanks for reporting!

**Comment by falkuh** [comment]
Tim,

could you post a notification under this item#-224 once a brew update is ready ?

best regards
falkuh

**Comment by tdsmith** [comment]
Sorry, I meant that you should run "brew update". Updates are published
immediately.
