### ISSUE TITLE
#226 not completely solved ?

### ISSUE THREAD

**Issue by puiseux** [Homebrew/homebrew-python#228]
I experience #226 issue with error
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/scipy/linalg/_fblas.so, 2): Library not loaded: /usr/local/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/scipy/linalg/_fblas.so
  Reason: image not found

I tried those commands : 
## Linking all packages
$ sudo ls -1 /usr/local/Library/LinkedKegs | while read line; do     echo $line;     brew unlink $line;     brew link --force $line; done
==> same error, 
N.B. : gcc4.9 was previously installed via brew, when linking gcc, i the expected (not sure!)  some brew-link message like this :
*gcc is keg-only and must be linked with --force*
i had **no such message**
## Updating brew
as suggested in #226 
$ brew update
==> same error, then : 

## Reinstall problematic packages

$ brew uninstall scipy
$ brew uninstall numpy
$ brew uninstall gcc
$ brew install gcc
$ brew install numpy
$ brew install scipy
==> same error.

## Finally in make by hand the missing link : 

$ cd /usr/local/lib/gcc/5
$ ln -s /usr/local/Cellar/gcc/5.1.0/lib/gcc/5/libgfortran.3.dylib .

==> it appears to be working

**Comment by tdsmith** [comment]
`/usr/local/lib/gcc` should be a symlink to `../Cellar/gcc/5.1.0/lib/gcc`. If it is not, `brew unlink gcc && brew prune && brew link gcc` may help. The packages are built correctly but there may be a problem with how the gcc library symlinks are installed. gcc is not a keg-only package.

Thanks for the report; if you discover how to reproduce this, please open an issue at Homebrew/homebrew.
