### ISSUE TITLE
Multiple versions of python3

### ISSUE THREAD

**Issue by erickwilder** [Homebrew/homebrew-python#231]
I'm looking for a repeatable (and possibly community-driven) solution to install different python3 versions (from 3.1 to 3.x) for MacOSX because I'm writing some libraries inside the company I work for and I want to help other open source libraries, which must be tested against several Python versions.

Is this project a good one to accept such contribution? If is not, what you recommend to solve this?

As a suggestion, I'm able to start writing formulas to install python with something line this:
```sh
brew install homebrew/python/python31
brew install homebrew/python/python32
brew install homebrew/python/python33
brew install homebrew/python/python34
```
Of course, none of those versions can be linked as default `python` command - this should be a decision of the user, by issuing `brew link python34` for example.

Thanks

**Comment by xu-cheng** [comment]
The recommended solution is using `pyenv`.

**Comment by erickwilder** [comment]
Nice! :+1:
