### ISSUE TITLE
Possible openssl error

### ISSUE THREAD

**Issue by michaeljs1990** [Homebrew/homebrew-python#232]
When i install python 2.7.10 through this package i get the following errors that you can see here https://github.com/ansible/ansible-modules-core/pull/1639. installing from python.org 2.7.10 fixes the issue using all the same packages. Does this seem like an issue in the way this is possibly being built or installed. It would be nice to use the homebrew version but I can't right now.

**Comment by tdsmith** [comment]
Please open an issue at Homebrew/homebrew describing in detail the problem you're encountering and why you think Homebrew should do something differently. Thanks!
