### ISSUE TITLE
No zlib on OS X 10.11

### ISSUE THREAD

**Issue by izzyleung** [Homebrew/homebrew-python#234]
Get the latest version of xcode-build installed, and when installing the latest version of python, the zlib failed to be installed.

```
Python 2.7.10 (default, Jul  4 2015, 15:33:55)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import zlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named zlib
>>>
```

This problem might be related to https://github.com/Homebrew/homebrew/issues/41085 and https://github.com/Homebrew/homebrew/issues/41255

**Comment by tdsmith** [comment]
Please file a new issue against Homebrew/homebrew and include the output of `brew gist-logs python`; thanks!

**Comment by tjanson** [comment]
For the record, for those coming via Google (as I did),
```
xcode-select --install
brew reinstall python3
```
should do the trick (in my case with El Capitan GM candidate 1). Confirm the existence of `zlib.h` with `ls /usr/include/zlib.h`.

More details in Homebrew/homebrew#41085 and [here](http://andinfinity.de/quick-note-homebrew-installed-python-fails-to-import-zlib/).

**Comment by rodriguezsergio** [comment]
@tjanson Thank you! El Capitan was driving me up the wall.

**Comment by tdsmith** [comment]
Installing the CLT should no longer be necessary if you're using Homebrew python; this bug explains why there are issues with recent Xcodes: https://bugs.python.org/issue25136
