### ISSUE TITLE
Must use Python with unicode enabled when including arrayobject.h

### ISSUE THREAD

**Issue by kilojoules** [Homebrew/homebrew-python#237]
I can't include numpy's `arrayobject.h` header file. I get an error message stating that I `Must use Python with unicode enabled`. To counter this, I tried `export LANG=cs_CZ.UTF-8` and `export PYTHONIOENCODING=utf-8`. However, I am unable to overcome this issue.

    $ cat ex.cpp 
    #include <numpy/arrayobject.h>

    $ clang -I/usr/local/lib/python2.7/site-packages/numpy/core/include ex.cpp 
    In file included from ex.cpp:1:
    In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17:
    In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:4:
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_common.h:164:9: error: unknown type name 'Py_intptr_t'
    typedef Py_intptr_t npy_intp;
            ^
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_common.h:165:9: error: unknown type name 'Py_uintptr_t'; did you mean 'uintptr_t'?
    typedef Py_uintptr_t npy_uintp;
            ^~~~~~~~~~~~
            uintptr_t
    /usr/include/sys/_types/_uintptr_t.h:30:24: note: 'uintptr_t' declared here
    typedef unsigned long           uintptr_t;
                                    ^
    In file included from ex.cpp:1:
    In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17:
    In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:4:
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_common.h:301:2: error: Must use Python with unicode enabled.
    #error Must use Python with unicode enabled.
     ^
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_common.h:949:9: error: unknown type name 'npy_uint16'
    typedef npy_uint16 npy_half;
            ^
    In file included from ex.cpp:1:
    In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17:
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:363:9: error: unknown type name 'PyObject'
    typedef PyObject * (PyArray_GetItemFunc) (void *, void *);
            ^
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:364:35: error: unknown type name 'PyObject'
    typedef int (PyArray_SetItemFunc)(PyObject *, void *, void *);
                                      ^
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:391:32: error: unknown type name 'FILE'
    typedef int (PyArray_ScanFunc)(FILE *fp, void *dptr,
                                   ^
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:513:9: error: unknown type name 'PyObject'
            PyObject *castdict;
            ^
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:573:9: error: unknown type name 'PyObject_HEAD'
            PyObject_HEAD
            ^
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:580:21: error: expected ';' at end of declaration list
            PyTypeObject *typeobj;
                        ^
                        ;
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:609:9: error: unknown type name 'PyObject'
            PyObject *fields;
            ^
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:614:9: error: unknown type name 'PyObject'
            PyObject *names;
            ^
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:621:9: error: unknown type name 'PyObject'
            PyObject *metadata;
            ^
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:632:9: error: unknown type name 'PyObject'
            PyObject *shape;       /* a tuple */
            ^
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:647:5: error: unknown type name 'PyObject_HEAD'
        PyObject_HEAD
        ^
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:649:5: error: expected member name or ';' after declaration specifiers
        char *data;
        ^
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:677:5: error: unknown type name 'PyObject'
        PyObject *base;
        ^
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:683:5: error: unknown type name 'PyObject'
        PyObject *weakreflist;
        ^
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:707:9: error: unknown type name 'PyObject_HEAD'
            PyObject_HEAD
            ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    $

**Comment by kilojoules** [comment]
I see now that python wasn't properly set up in my code to import numy, but why doesn't this work?

```
int main(){
#include <Python.h>
Py_Initialize();
#include <numpy/arrayobject.h>
Py_Finalize();
};
```

**Comment by tdsmith** [comment]
Including headers inside the body of main() is a weird thing to do in C.

**Comment by kilojoules** [comment]
@tdsmith OK. I did this out of confusion from my original error, using `#include <numpy/arrayobject.h>`. Please disregard the int main() comment.

**Comment by tdsmith** [comment]
Is there a remaining issue?

**Comment by kilojoules** [comment]
@tdsmith Yes. `#include <numpy/arrayobject.h>` leads to several errors, one of which refers to python's unicode abilities. 

    $ cat ex.hpp 
    #include <numpy/arrayobject.h>
    
    ....
    fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by kilojoules** [comment]
I am able to `#include <numpy/arrayobject.h>` when compiling established source codes. I must be doing something wrong

**Comment by tdsmith** [comment]
It looks like you need to include Python.h first.

**Comment by tdsmith** [comment]
Let us know if this is still an issue or if we can help with anything else.
