### ISSUE TITLE
brew install numpy error

### ISSUE THREAD

**Issue by spencersalazar** [Homebrew/homebrew-python#239]
I am getting an error when I try to install numpy with python3. 

    $ brew install numpy --without-python --with-python3
    ==> Installing numpy from homebrew/homebrew-python
    ==> Using Homebrew-provided fortran compiler.
    This may be changed by setting the FC environment variable.
    ==> Downloading https://downloads.sourceforge.net/project/numpy/NumPy/1.9.2/numpy-1.9.2.tar.gz
    ==> Downloading from http://downloads.sourceforge.net/#!/project/numpy/NumPy/1.9.2/numpy-1.9.2.tar.gz
    ######################################################################## 100.0%
    Error: SHA256 mismatch
    Expected: 325e5f2b0b434ecb6e6882c7e1034cc6cdde3eeeea87dbc482575199a6aeef2a
    Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
    Archive: /Library/Caches/Homebrew/numpy-1.9.2.tar.gz
    To retry an incomplete download, remove the file above.

**Comment by dunn** [comment]
This is because SourceForge is still having serious issues: https://github.com/Homebrew/homebrew/issues/41778. Afraid there's nothing we can do!

**Comment by tdsmith** [comment]
Let's switch to pypi; they have a better CDN anyway.
