### ISSUE TITLE
Pygame for Python 3

### ISSUE THREAD

**Issue by kenzierocks** [Homebrew/homebrew-python#248]
`pygame` doesn't appear to support Python 3 via `--with-python3`. Could this be added?

**Comment by tdsmith** [comment]
Sure, if pygame supports it. Here's some guidance on submitting a pull request: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by tdsmith** [comment]
Closed by #249 (thanks!)
