### ISSUE TITLE
Error: Failed to update tap: samueljohn/python

### ISSUE THREAD

**Issue by DaveEveritt** [Homebrew/homebrew-python#268]
I'm running (and need to maintain Python 2.7.9) but on `brew update` got the above error. I presume this now needs to read from homebrew/python. How to correct this?

**Comment by tdsmith** [comment]
It should forward transparently. Running `brew untap samueljohn/python` and `brew tap homebrew/python` shouldn't do anything surprising, in any case. Let us know if we can help with anything else.

**Comment by DaveEveritt** [comment]
thanks - that does the job.
