### ISSUE TITLE
pyplot - ImportError: No module named _tkinter

### ISSUE THREAD

**Issue by kilojoules** [Homebrew/homebrew-python#270]
I am struggling to make basic plots in matplotlib. It looks like I'm not installing tkinter correctly, which I understand should be installed from the `--with-tcl-tk` flag. 

I uninstalled then reinstalled everything I thought was relevant. No errors were raised by brew.

    $ brew uninstall python
    $ brew uninstall matplotlib numpy --force
    $ brew install python --with-tcl-tk
    $ brew install numpy matplotlib --with-tcl-tk

However, I get an error when I import pyplot:

    $ python
    Python 2.7.11 (default, Dec 22 2015, 12:47:31) 
    [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from matplotlib import pyplot
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 109, in <module>
        _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
      File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
        globals(),locals(),[backend_name],0)
      File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
        from six.moves import tkinter as Tk
      File "/usr/local/lib/python2.7/site-packages/six.py", line 199, in load_module
        mod = mod._resolve()
      File "/usr/local/lib/python2.7/site-packages/six.py", line 113, in _resolve
        return _import_module(self.mod)
      File "/usr/local/lib/python2.7/site-packages/six.py", line 80, in _import_module
        __import__(name)
      File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
        import _tkinter # If this fails your Python may not be configured for Tk
    ImportError: No module named _tkinter
    >>>

**Comment by tdsmith** [comment]
Can you share the output of `brew gist-logs python` and `brew gist-logs matplotlib`?

**Comment by kilojoules** [comment]
Thank you for taking a look at this @tdsmith. 

    $ brew gist-logs python
    https://gist.github.com/bdc2fe094d1265a983ec
    $ brew gist-logs matplotlib
    https://gist.github.com/d6bdc2d4c93246b80abc

**Comment by tdsmith** [comment]
> It looks like this could be the cause of my problem... Does this build rely on system tkinter?

I think it is the cause of your problem. Python with --with-tcl-tk should not be relying on system Tcl/Tk. Is your system Tcl/Tk intact, though?

The problem is announced here: "INFO: Can't locate Tcl/Tk libs and/or headers" at https://gist.github.com/anonymous/bdc2fe094d1265a983ec#file-02-make-L174

**Comment by kilojoules** [comment]
The system tcl/tk may be corrupt. I'm not sure how to test it.

**Comment by kilojoules** [comment]
I reinstalled tcl with X11 `brew install homebrew/dupes/tcl-tk --with-x11` 

and now I'm faced with this error:

     python -c "import matplotlib.pyplot"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 109, in <module>
        _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
      File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
        globals(),locals(),[backend_name],0)
      File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 13, in <module>
        import matplotlib.backends.tkagg as tkagg
      File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/tkagg.py", line 7, in <module>
        from matplotlib.backends import _tkagg
    ImportError: cannot import name _tkagg

**Comment by kilojoules** [comment]
Somehow `$ brew install matplotlib --with-gtk+3 --with-pygtk --with-pyqt --with-pyqt5 --with-pyside` fixed my problem

**Comment by kilojoules** [comment]
Is this a homebrew-python issue or homebrew issue?

**Comment by tdsmith** [comment]
It is not clearly either to me.

**Comment by kilojoules** [comment]
I had deleted a _tkagg file in /System, and homebrew python still relies on this file. Upgrading to the newest version of the osx operating system solved this issue for me

**Comment by marvinosswald** [comment]
Doesn't work for me neither, reinstalled matplotlib with `brew install homebrew/python/matplotlib --with-tcl-tk` still no luck..

- python installed by brew with `--with-tcl-tk` flag
- tkinter installed with `homebrew/dupes/tcl-tk`

error:

```
  File "/Users/marvin/dev/py/teachSurface/Start.py", line 60, in <module>
    app = GUI(root)
  File "/Users/marvin/dev/py/teachSurface/Gui.py", line 29, in __init__
    canvas.show()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 355, in draw
    tkagg.blit(self._tkphoto, self.renderer._renderer, colormode=2)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/tkagg.py", line 30, in blit
    id(data), colormode, id(bbox_array))
_tkinter.TclError
```

**Comment by tdsmith** [comment]
Please open a new ticket and provide the same outputs I requested from @kilojoules; thanks!

**Comment by kilojoules** [comment]
@tdsmith I am confused about the intended use of the `--with-tcl-tk` option. When I read `Use Homebrew's tk instead of OS X Tk`, I thought it meant that this installation was completely independent of Homebrew tk. As my issue demonstrated, homebrew python always relies on the osx tk. If this is intended then this description is misleading IMO.

**Comment by tdsmith** [comment]
Please file against homebrew/homebrew if you're running into troubles that manifest as a result; thanks!

**Comment by tdsmith** [comment]
@ilovezfs points out that matplotlib is additionally linking against system tcl/tk, which seems like an error with this package; I have no insight wrt fixing it

**Comment by kilojoules** [comment]
As noted above I was using homebrew matplotlib which also has a `--with-tcl-tk` option

**Comment by tdsmith** [comment]
There are at least two separate issues here; one is whether Python can figure out how to build a _tkinter module (and whether the built module is correct) during the Python build process and the other is whether matplotlib links to the correct Tk during the matplotlib build process; @ilovezfs informs me that matplotlib really does link against a Tk library instead of using the Python interface, which I hadn't appreciated.

The fix should be removing the option or fixing the behavior.

**Comment by hlin117** [comment]
I followed @kilojoules's comment [here](https://github.com/Homebrew/homebrew-python/issues/270#issuecomment-170200287), but it still looks like I get the error
```
importError: No module named _tkinter
```
I'm seriously considering a clean install of python right now from the package source, with the appropriate options...

**Comment by tdsmith** [comment]
Please open a new ticket and provide the same outputs I requested from @kilojoules; thanks!
