### ISSUE TITLE
numpy/scipy: failed tests are treated as success

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew-python#273]
To reproduce:
```
brew rm gcc
brew test numpy -v
echo $?
brew test scipy -v
echo $?
```

You will see the tests are failing but Hombrew treats them as success.

**Comment by xu-cheng** [comment]
cc @tdsmith

**Comment by tdsmith** [comment]
the numpy test invocation is wrong; the scipy test invocation is questionable since we should probably fail on "errors" (test could not run) as well as "failures" (test gave wrong answer)
