### ISSUE TITLE
Pygame Formula on OS X El Capitan causes graphical glitching

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-python#281]
_From @saltycraig on January 29, 2016 14:20_

The pygame formula installs sdl_image 1.2.12, which it seems has a bug/compatibility error with El Capitan that causes many graphical glitches when running python games built with pygame. The formula should be rewritten to install sdl_image 1.2.10 instead for now (which fixes the issues) until it is resolved (unknown who or when/if this might be fixed). See relevant discussion here:

http://stackoverflow.com/questions/33115482/rendering-glitch-on-mac-osx-el-capitan-with-opengl/35075170#35075170

_Copied from original issue: Homebrew/homebrew#48594_

**Comment by s172262** [comment]
Now pygame can load png image on El Capitan. 
Should you replace to repaired sdl_image 1.2.12 of https://github.com/Homebrew/homebrew-core/pull/281.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
