### ISSUE TITLE
vpython does not work with wxwidgets version 3.0.2

### ISSUE THREAD

**Issue by schodet** [Homebrew/homebrew-python#286]
Since wxwidgets version 3.0.2, vpython is not usable as the rate function only returns when there is some mouse mouvements, see : https://groups.google.com/forum/?fromgroups&hl=en#!searchin/vpython-users/rate/vpython-users/sIjW42s3V2w/1DkCYlDLBgAJ

I changes my formulae locally to build wxmac and wxpython at version 3.0.0 and it works.

What whould be the best way to handle this problem? Should vpython depend on a specific version (using homebrew/versions tap)?

**Comment by tdsmith** [comment]
Creating a versions tap for wxpython is possible; ideally this would be resolved by a bugfix patch committed upstream to one package or the other.

**Comment by schodet** [comment]
I filled a issue for vpython : https://github.com/BruceSherwood/vpython-wx/issues/79

Do you want me to try to write a formula in the versions tap? Can I change the vpython formula to depend on this versions formula?

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
