### ISSUE TITLE
Unable to install gubbins

### ISSUE THREAD

**Issue by bineetuwa** [Homebrew/homebrew-python#292]
Hi, Can you please help me install gubbins. I get following message when I do: _brew install gubbins_
==> Installing gubbins from homebrew/science
==> Installing dependencies for homebrew/science/gubbins: homebrew/python
==> Installing homebrew/science/gubbins dependency: homebrew/python/numpy
==> Using a fortran compiler found at /usr/bin/gfortran.
This may be changed by setting the FC environment variable.
==> Downloading https://pypi.python.org/packages/source/n/numpy/numpy-1.10.4.tar
Already downloaded: /home/hplab/.cache/Homebrew/numpy-1.10.4.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/nose/nose-1.3.7.tar.gz
Already downloaded: /home/hplab/.cache/Homebrew/numpy--nose-1.3.7.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/home/hplab/.l
==> python setup.py build --fcompiler=gnu95 install --prefix=/home/hplab/.linuxb
==> Downloading https://pypi.python.org/packages/source/n/nose/nose-1.3.7.tar.gz
Already downloaded: /home/hplab/.cache/Homebrew/numpy--nose-1.3.7.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/home/hplab/.
Last 15 lines from /home/hplab/.cache/Homebrew/Logs/numpy/03.python3:
python3
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/home/hplab/.linuxbrew/Cellar/numpy/1.10.4/libexec/nose
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'setuptools'

READ THIS: https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-python/issues

These open issues may also help:
numpy: builds and installs after standalone brew https://github.com/Linuxbrew/linuxbrew/issues/455

**Comment by ilovezfs** [comment]
What's the output of
```
which -a python
```

**Comment by bineetuwa** [comment]
/user/bin/python

**Comment by ilovezfs** [comment]
And `which -a python3`

**Comment by bineetuwa** [comment]
/usr/bin/python3
/home/hp-lab/.linuxbrew/bin/python3

**Comment by ilovezfs** [comment]
Can you try
```
echo 'export PATH=/home/hp-lab/.linuxbrew/bin:$PATH' >> ~/.bash_profile
source ~/.bash_profile
brew uninstall numpy
brew uninstall pillow
brew install gubbins
```

**Comment by bineetuwa** [comment]
I got following message for: _brew uninstall numpy_
Error: No such keg: /home/hplab/.linuxbrew/Cellar/numpy

**Comment by ilovezfs** [comment]
That's fine.

**Comment by bineetuwa** [comment]
Wow, that worked perfectly. Thank you very much for your help.

**Comment by ilovezfs** [comment]
@bineetuwa You're welcome.
