### ISSUE TITLE
Matplotlib-basemap installation does not import

### ISSUE THREAD

**Issue by dheerajchand** [Homebrew/homebrew-python#298]
Hi! I am relatively new to Homebrew and I am trying to learn MatPlotLib and Basemap. I followed the instructions [here](https://github.com/obspy/obspy/wiki/Installation-on-OS-X-using-Homebrew) to install using `brew`, but it did not seem to take.  

Post-installation, I am trying the instructions from [here](http://matplotlib.org/basemap/users/merc.html). What am I doing wrong?
Here's what I have:

> dheerajchand@Dheerajs2016MBP:~|⇒  which python
> /usr/local/bin/python
> dheerajchand@Dheerajs2016MBP:~|⇒  rm -rf ~/Python/geo
> dheerajchand@Dheerajs2016MBP:~|⇒  pip freeze                      
> ansible==2.0.1.0
> basemap==1.0.7
> cycler==0.9.0
> ecdsa==0.13
> funcsigs==0.4
> GDAL==1.11.3
> Jinja2==2.8
> MarkupSafe==0.23
> matplotlib==1.5.1
> mock==1.3.0
> nose==1.3.7
> numpy==1.11.0
> paramiko==1.16.0
> pbr==1.8.1
> Pillow==3.2.0
> pycrypto==2.6.1
> pyparsing==2.0.6
> python-dateutil==2.4.2
> pytz==2015.7
> PyYAML==3.11
> scipy==0.17.0
> six==1.10.0
> stevedore==1.12.0
> vboxapi==1.0
> virtualenv==15.0.1
> virtualenv-clone==0.2.6
> virtualenvwrapper==4.7.1
> wxPython==3.0.2.0
> wxPython-common==3.0.2.0
> dheerajchand@Dheerajs2016MBP:~|⇒  mkvirtualenv --system-site-packages geo
> New python executable in /Users/dheerajchand/Python/geo/bin/python
> Installing setuptools, pip, wheel...done.
> virtualenvwrapper.user_scripts creating /Users/dheerajchand/Python/geo/bin/predeactivate
> virtualenvwrapper.user_scripts creating /Users/dheerajchand/Python/geo/bin/postdeactivate
> virtualenvwrapper.user_scripts creating /Users/dheerajchand/Python/geo/bin/preactivate
> virtualenvwrapper.user_scripts creating /Users/dheerajchand/Python/geo/bin/postactivate
> virtualenvwrapper.user_scripts creating /Users/dheerajchand/Python/geo/bin/get_env_details
> dheerajchand@Dheerajs2016MBP:~|⇒  workon geo 
> dheerajchand@Dheerajs2016MBP:~|⇒  pip freeze
> altgraph==0.10.2
> ansible==2.0.1.0
> bdist-mpkg==0.5.0
> bonjour-py==0.3
> ecdsa==0.13
> Jinja2==2.8
> macholib==1.5.1
> MarkupSafe==0.23
> matplotlib==1.3.1
> modulegraph==0.10.4
> numpy==1.8.0rc1
> paramiko==1.16.0
> pbr==1.8.1
> py2app==0.7.3
> pycrypto==2.6.1
> pyobjc-core==2.5.1
> pyobjc-framework-Accounts==2.5.1
> pyobjc-framework-AddressBook==2.5.1
> pyobjc-framework-AppleScriptKit==2.5.1
> pyobjc-framework-AppleScriptObjC==2.5.1
> pyobjc-framework-Automator==2.5.1
> pyobjc-framework-CFNetwork==2.5.1
> pyobjc-framework-Cocoa==2.5.1
> pyobjc-framework-Collaboration==2.5.1
> pyobjc-framework-CoreData==2.5.1
> pyobjc-framework-CoreLocation==2.5.1
> pyobjc-framework-CoreText==2.5.1
> pyobjc-framework-DictionaryServices==2.5.1
> pyobjc-framework-EventKit==2.5.1
> pyobjc-framework-ExceptionHandling==2.5.1
> pyobjc-framework-FSEvents==2.5.1
> pyobjc-framework-InputMethodKit==2.5.1
> pyobjc-framework-InstallerPlugins==2.5.1
> pyobjc-framework-InstantMessage==2.5.1
> pyobjc-framework-LatentSemanticMapping==2.5.1
> pyobjc-framework-LaunchServices==2.5.1
> pyobjc-framework-Message==2.5.1
> pyobjc-framework-OpenDirectory==2.5.1
> pyobjc-framework-PreferencePanes==2.5.1
> pyobjc-framework-PubSub==2.5.1
> pyobjc-framework-QTKit==2.5.1
> pyobjc-framework-Quartz==2.5.1
> pyobjc-framework-ScreenSaver==2.5.1
> pyobjc-framework-ScriptingBridge==2.5.1
> pyobjc-framework-SearchKit==2.5.1
> pyobjc-framework-ServiceManagement==2.5.1
> pyobjc-framework-Social==2.5.1
> pyobjc-framework-SyncServices==2.5.1
> pyobjc-framework-SystemConfiguration==2.5.1
> pyobjc-framework-WebKit==2.5.1
> pyOpenSSL==0.13.1
> pyparsing==2.0.1
> python-dateutil==1.5
> pytz==2013.7
> PyYAML==3.11
> scipy==0.13.0b1
> six==1.10.0
> stevedore==1.12.0
> vboxapi==1.0
> virtualenv==15.0.1
> virtualenv-clone==0.2.6
> virtualenvwrapper==4.7.1
> xattr==0.6.4
> zope.interface==4.1.1
> dheerajchand@Dheerajs2016MBP:~|⇒  pip install geopandas
> Collecting geopandas
> Collecting pyproj (from geopandas)
> Collecting descartes (from geopandas)
>   Using cached descartes-1.0.2-py2-none-any.whl
> Collecting fiona (from geopandas)
>   Using cached Fiona-1.6.3.post1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
> Collecting pandas (from geopandas)
>   Using cached pandas-0.18.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
> Collecting shapely (from geopandas)
>   Using cached Shapely-1.5.15-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
> Requirement already satisfied (use --upgrade to upgrade): six in /Library/Python/2.7/site-packages (from fiona->geopandas)
> Collecting cligj (from fiona->geopandas)
>   Using cached cligj-0.4.0-py2-none-any.whl
> Collecting click-plugins (from fiona->geopandas)
> Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pandas->geopandas)
> Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pandas->geopandas)
> Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.0 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from pandas->geopandas)
> Collecting click>=4.0 (from cligj->fiona->geopandas)
> Installing collected packages: pyproj, descartes, click, cligj, click-plugins, fiona, pandas, shapely, geopandas
> Successfully installed click-6.6 click-plugins-1.0.3 cligj-0.4.0 descartes-1.0.2 fiona-1.6.3.post1 geopandas-0.1.1 pandas-0.18.0 pyproj-1.9.5.1 shapely-1.5.15
> 
> (installed ipython)
> 
> dheerajchand@Dheerajs2016MBP:~|⇒  ipython
> Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 4.2.0 -- An enhanced Interactive Python.
> ?         -> Introduction and overview of IPython's features.
> %quickref -> Quick reference.
> help      -> Python's own help system.
> object?   -> Details about 'object', use 'object??' for extra details.
> 
> In [1]: import geopandas
> 
> In [2]: import matplotlib
> 
> In [3]: from mpl_toolkits.basemap import Basemap
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-3-5e6824321d57> in <module>()
> ----> 1 from mpl_toolkits.basemap import Basemap
> 
> ImportError: No module named basemap
> 
> In [4]:

**Comment by tdsmith** [comment]
It's present before you created your virtualenv so I think the problem you're having is with that step and perhaps not with Homebrew.

**Comment by dheerajchand** [comment]
Those packages were installed into the Homebrew Python when I ran the 'brew install' line in the tutorial, which is why I thought I would have to use the site packages flag. Are you telling me that it would have worked in the virtual environment if I had not use that flag? I'll try that and post the results.

**Comment by dheerajchand** [comment]
It turns out that for whatever reason, this will work in the Homebrew python, but not port over to a virtualenv created off the python. Any suggestions as to why?

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
