### ISSUE TITLE
matplotlib using OS X 'Python.app' instead of X11, regardless of backend

### ISSUE THREAD

**Issue by dshean** [Homebrew/homebrew-python#313]
I recently upgraded to El Capitan.  I encountered the issue described below, and decided to do a fresh homebrew install.  Even with a fresh install, I'm experiencing the same issue.

I use ipython and matplotlib remotely with X11 forwarding to display plots.  In the past, I've always used the GTKAgg backend for this, and it has worked well.

I installed necessary gtk+, gtk+3, pygtk deps, and then matplotlib:

brew install matplotlib --with-cairo --with-ghostscript --with-gtk+3 --with-pygtk --with-tex

In my matplotlibrc, I specify 'backend : GTKAgg', and when I start ipython I get 'Using matplotlib backend: GTKAgg' confirmation.

Everything is fine, but when I import matplotlib.pyplot, a "Python.app" is opened (/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/Resources/Python.app) and used for all plot display.  Same commands with earlier install would open with X11 window.  

I'm sure it's some simple config option that I'm missing, but I can't seem to figure it out.   

brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2c792076dc58e871bb7cd2a4cb4d03c39770497d
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c03ac18f93222491efda14cfff9a66602ae70def
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit penryn
Clang: 7.3 build 703
Git: 2.7.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
System Ruby: 2.0.0-p648
OS X: 10.11.5-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11

**Comment by tdsmith** [comment]
Homebrew's GTK doesn't use X11 anymore, sorry.

**Comment by dshean** [comment]
OK, so what are my options?  Use an earlier version of the gtk+ formula?

The answer here offers some insight, but no solution:
http://apple.stackexchange.com/questions/205404/how-can-i-get-gdk-x11-3-0-on-os-x
