### ISSUE TITLE
pygame might need upgrading (1.9.2b6)

### ISSUE THREAD

**Issue by Numbermaniac** [Homebrew/homebrew-python#322]
The version of [Pygame](https://github.com/Homebrew/homebrew-python/blob/master/pygame.rb) here is 1.9.2a0, whereas the one on pip is [1.9.2b6](https://pypi.python.org/pypi/Pygame/1.9.2b6). I don't know what to change in the formula though...

**Comment by niccokunzmann** [comment]
@Numbermaniac Have a look at [line 5](https://github.com/Homebrew/homebrew-python/blob/master/pygame.rb#L5). This should be the git-revision. I think, if you change this to the updated git revision, it should suffice.

**Comment by tdsmith** [comment]
If you can find a versioned tarball, please replace the `url` with a link to it! I picked a random prerelease commit because the build was broken with all released versions.

**Comment by niccokunzmann** [comment]
I did a pip install lately and it worked. I guess, almost any version could be used.

**Comment by Numbermaniac** [comment]
Is it theoretically possible to just download the wheel from pip and then automatically install it with pip?

**Comment by tdsmith** [comment]
Yes, theoretically. This tap prefers to build from sdist and doesn't assume that pip is installed.

**Comment by tsparber** [comment]
Fix proposed in #360.

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/homebrew-python/issues/360
