### ISSUE TITLE
Problem installing gubbins in Ubuntu 16.04

### ISSUE THREAD

**Issue by bineetuwa** [Homebrew/homebrew-python#326]
Hi I used homebrew to install gubbins and it's showing following error:

hplab@hplab-Inspiron-5559:~$ brew install gubbins
==> Installing gubbins from homebrew/science
==> Installing dependencies for homebrew/science/gubbins: homebrew/python
==> Installing homebrew/science/gubbins dependency: homebrew/python/numpy
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://files.pythonhosted.org/packages/e0/4c/515d7c4ac424ff38cc
Already downloaded: /home/hplab/.cache/Homebrew/numpy-1.11.1.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/nose/nose-1.3.7.tar.gz
Already downloaded: /home/hplab/.cache/Homebrew/numpy--nose-1.3.7.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/home/hplab/.l
==> python setup.py build --fcompiler=gnu95 --parallel=4 install --prefix=/home/
==> python -c import numpy; assert numpy.test().wasSuccessful()
Last 15 lines from /home/hplab/.cache/Homebrew/Logs/numpy/03.python:

----------------------------------------------------------------------
Ran 6151 tests in 53.416s

FAILED (KNOWNFAIL=6, SKIP=13, errors=1)
Running unit tests for numpy
NumPy version 1.11.1
NumPy relaxed strides checking option: False
NumPy is installed in /home/hplab/.linuxbrew/Cellar/numpy/1.11.1/lib/python2.7/site-packages/numpy
Python version 2.7.12 (default, Jul 26 2016, 16:15:49) [GCC 5.4.0 20160609]
nose version 1.3.7
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-python/issues)

Any help is appretiated.

**Comment by tdsmith** [comment]
> READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please include the output of `brew gist-logs numpy`; there's not enough here to troubleshoot with. Thanks!

**Comment by bineetuwa** [comment]
https://gist.github.com/f7b8bfb8b0b008d3b28293f2d35e4449

**Comment by tdsmith** [comment]
This should have been fixed by 4c5a6fe9fe. Have you run `brew update` recently?

**Comment by bineetuwa** [comment]
Thank you very much. Not running brew update recently was the problem.

**Comment by tdsmith** [comment]
Great, thanks!
