### ISSUE TITLE
Numpy HEAD builds require cython

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-python#330]
_From @aw1621107 on August 29, 2016 20:8_

This was with `brew install numpy --with-python3 --HEAD`

```
==> python setup.py build --fcompiler=gnu95 --parallel=8 install --prefix=/usr/local/Cellar/numpy/HEAD-a93d9f7 --single-version-externally-managed --record=installed.txt
Running from numpy source directory.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named Cython.Compiler.Main
Processing numpy/random/mtrand/mtrand.pyx
Traceback (most recent call last):
  File "/private/tmp/numpy-20160829-65969-143uv2/tools/cythonize.py", line 199, in <module>
    main()
  File "/private/tmp/numpy-20160829-65969-143uv2/tools/cythonize.py", line 195, in main
    find_process_files(root_dir)
```

Running `pip3 install cython` and `pip install cython` fixed the issue.

Is Homebrew capable of doing such a check and/or installing the package in question?

_Copied from original issue: Homebrew/homebrew-science#4163_

**Comment by tdsmith** [comment]
_From @dpo on August 30, 2016 2:0_

This should be reported over at [homebrew/python](https://github.com/Homebrew/homebrew-python/issues).

**Comment by tdsmith** [comment]
This only applies to HEAD builds; the sdists are pre-cythonized. You can grep around to find some other formulas that vendor cython as a resource; we can do something similar here for HEAD builds.

**Comment by aw1621107** [comment]
Hm, didn't know that. I'll take a look.

**Comment by dpo** [comment]
See, e.g., https://github.com/Homebrew/homebrew-python/blob/f81ba718963ac20ae64adbfdfda2a37b2091f498/mpi4py.rb#L18.
