### ISSUE TITLE
matplotlib

### ISSUE THREAD

**Issue by fhimpe** [Homebrew/homebrew-python#332]
When importing matplotlib here on a system running OS X El Capitan, it fails with this error:
`
$ python
Python 2.7.12 (default, Aug 29 2016, 15:09:56) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import matplotlib
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/site-packages/matplotlib/**init**.py", line 1131, in <module>
> > >     rcParams = rc_params()
> > >   File "/usr/local/lib/python2.7/site-packages/matplotlib/**init**.py", line 975, in rc_params
> > >     return rc_params_from_file(fname, fail_on_error)
> > >   File "/usr/local/lib/python2.7/site-packages/matplotlib/**init**.py", line 1100, in rc_params_from_file
> > >     config_from_file = _rc_params_in_file(fname, fail_on_error)
> > >   File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
> > >     with _open_file_or_url(fname) as fd:
> > >   File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
> > >     return self.gen.next()
> > >   File "/usr/local/lib/python2.7/site-packages/matplotlib/**init**.py", line 1000, in _open_file_or_url
> > >     encoding = locale.getdefaultlocale()[1]
> > >   File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 545, in getdefaultlocale
> > >     return _parse_localename(localename)
> > >   File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 477, in _parse_localename
> > >     raise ValueError, 'unknown locale: %s' % localename
> > > ValueError: unknown locale: UTF-8

`

Upstream has this patch fixing this issue: https://github.com/matplotlib/matplotlib/commit/2ac494f71676e8cf824ae7eced1bca0848bb5a59

Could this be added to Homebrew?

**Comment by ilovezfs** [comment]
Closing as stale since upstream has now released 2.0.0.
