### ISSUE TITLE
environment variable to enable --with-python3 by default

### ISSUE THREAD

**Issue by AlJohri** [Homebrew/homebrew-python#334]
Hi @tdsmith,

I was wondering if its possible to add an environment variable which will default to always add the `--with-python3` command line parameter. I keep forgetting to add it and end up uninstalling and reinstalling the package.

This could be similar to the `HOMEBREW_CASK_OPTS` environment variable used like: 
```
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
```

Perhaps, `HOMEBREW_PYTHON_OPTS` or more generically `HOMEBREW_OPTS` (but that sounds more dangerous).

Thanks!

**Comment by tdsmith** [comment]
This seems like a good issue to raise on the Homebrew/brew-evolution tracker.

**Comment by tdsmith** [comment]
Alternatively: `alias brew=brew --with-python` :o
