### ISSUE TITLE
python 3 bottles?

### ISSUE THREAD

**Issue by AlJohri** [Homebrew/homebrew-python#335]
Hi all,

I was wondering if its possible to include python 3 bottles, at least for the super commonly used packages like numpy.

I saw this issue https://github.com/Homebrew/homebrew-python/issues/214 that spoke of potentially creating some DSLs like `py_bottle` and `py3_bottle`.

I was wondering if any progress was made on this. Thanks!

cc @tdsmith @xu-cheng

**Comment by tdsmith** [comment]
No progress. We'd have to introduce build dependencies on python3, which might get annoying, and we'd have to rebuild the world when we upgraded python3 to a new minor version, which is probably not too bad.

**Comment by MikeMcQuaid** [comment]
Sorry, passing on this for now. We're not going to create a DSL for non-default bottle options.
