### ISSUE TITLE
pymssql 2.1.1  :  undeclared identifer: DBVERSION_80;

### ISSUE THREAD

**Issue by bronlib** [Homebrew/homebrew-python#338]
this sounds exactly like the issue what existed for freetds, but now for pymssql, namely 

undeclared identifier 'DBVERSION_80'

Installed /private/tmp/pymssql-20160915-35787-1qxjtez/pymssql-2.1.1/.eggs/setuptools_git-1.1-py2.7.egg
running install
running build
running build_ext
building '_mssql' extension
creating build
creating build/temp.macosx-10.11-x86_64-2.7
clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _mssql.c -o build/temp.macosx-10.11-x86_64-2.7/_mssql.o -DMSDBLIB
_mssql.c:16504:15: error: use of undeclared identifier 'DBVERSION_80'
    __pyx_r = DBVERSION_80;
              ^
1 error generated.
error: command 'clang' failed with exit status 1

**Comment by bronlib** [comment]
after going to pymssql, I successfully install pymssql-2.2.0.dev0-py2.7-macosx-10.11-x86_64.egg

so perhaps the easiest resolution is to link the version 2.2.0 in brew

**Comment by tdsmith** [comment]
https://github.com/pymssql/pymssql/issues/432

2.2.0 hasn't been released yet

**Comment by MikeMcQuaid** [comment]
This formula was removed so closing.

**Comment by jzaleski** [comment]
Until `v2.2.0` has been blessed/released, as it is still in development, where the core issue resolved, you can use the following tag on our fork here: https://github.com/wayfair/pymssql/releases/tag/v2.1.3.0.0.1 -- it _has_ the necessary patch to resolve the original issue.
