### ISSUE TITLE
error: command 'clang' failed with exit status 1

### ISSUE THREAD

**Issue by brunobolandini** [Homebrew/homebrew-python#339]
When installing PyGame via Homebew i got the error:

1 error generated.
error: command 'clang' failed with exit status 1

Dont know what to do. Any help?

**Comment by mpriscella** [comment]
I'm noticing the same thing when trying to install `homebrew/versions/ansible19`.

Looks like it can't find the `ffi` header file.

```
clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c c/_cffi_backend.c -o build/temp.macosx-10.12-intel-2.7/c/_cffi_backend.o
c/_cffi_backend.c:15:10: fatal error: 'ffi.h' file not found
#include <ffi.h>
         ^
1 error generated.
error: command 'clang' failed with exit status 1
```

I've run `brew update` and `brew doctor` multiple times with no success, I also made sure the Xcode 8 command line tools are installed and active.

**Comment by robwilkerson** [comment]
For whatever it's worth, I see the exact same issue when attempting to install an earlier version of Ansible.

```
brew install homebrew/versions/ansible20
```

**Comment by tdsmith** [comment]
Please file issues with homebrew/versions formula against homebrew/versions with the output of `brew gist-logs some_formula`.

For pygame, please open a new issue with the output of `brew gist-logs pygame`.
