### ISSUE TITLE
Error Installing pysvn on MacOS Sierra

### ISSUE THREAD

**Issue by brileyd** [Homebrew/homebrew-python#347]
I get the following error when attempting to install pysvn:

mymbp - [10/11/16 17:16:02]:brew install pysvn
==> Installing pysvn from homebrew/python
==> Downloading http://pysvn.barrys-emacs.org/source_kits/pysvn-1.9.2.tar.gz
Already downloaded: /Users/doylebriley/Library/Caches/Homebrew/pysvn-1.9.2.tar.gz
==> python setup.py configure --link-python-framework-via-dynamic-lookup
Last 15 lines from /Users/doylebriley/Library/Logs/Homebrew/pysvn/01.python:
2016-10-11 17:16:09 -0500

python
setup.py
configure
--link-python-framework-via-dynamic-lookup

Info: Configure for python 2.7.10 in exec_prefix /System/Library/Frameworks/Python.framework/Versions/2.7
('Error:', 'Set environment variable MACOSX_DEPLOYMENT_TARGET to desired target')

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-python/issues

**Comment by tdsmith** [comment]
Can't reproduce; please share `brew gist-logs pysvn`.

**Comment by e0ne** [comment]
Confirmed, http://paste.openstack.org/show/586768/

**Comment by tdsmith** [comment]
Please share brew gist-logs pysvn.

**Comment by e0ne** [comment]
https://gist.github.com/10d4765d1851cb8e36140c4098665337

**Comment by tdsmith** [comment]
It looks like you can work around this with `sudo xcode-select --install` to install the CLT but it looks a little bit confused anyway; it needs some help finding the right include paths.

**Comment by MikeMcQuaid** [comment]
Closing as there's a workaround available.
