### ISSUE TITLE
download url changed

### ISSUE THREAD

**Issue by iGhoneim** [Homebrew/homebrew-python#348]
cpyrit-opencl
it's not https://pyrit.googlecode.com/files/pyrit-0.4.0.tar.gz any more
use https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/pyrit/cpyrit-opencl-0.4.0.tar.gz instead

**Comment by tdsmith** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? [This document](https://git.io/vo2xc) should give you a head start and we'd be more than happy to walk you through it if you have any questions.

**Comment by iGhoneim** [comment]
@tdsmith This Document = HTTP 404

**Comment by tdsmith** [comment]
Fixed by @e0ne; thanks!
