### ISSUE TITLE
numpy 1.11.2 fails a test

### ISSUE THREAD

**Issue by itsayellow** [Homebrew/homebrew-python#353]
I've never had a problem with the homebrew numpy until now, and on multiple computers the numpy upgrade fails because it fails a test from assert numpy.test().wasSuccessful()

```
==> python -c import numpy; assert numpy.test().wasSuccessful()
Last 15 lines from /Users/mclapp/Library/Logs/Homebrew/numpy/03.python:


----------------------------------------------------------------------
Ran 6128 tests in 50.846s

FAILED (KNOWNFAIL=6, SKIP=7, errors=1)
Running unit tests for numpy
NumPy version 1.11.2
NumPy relaxed strides checking option: False
NumPy is installed in /usr/local/Cellar/numpy/1.11.2/lib/python2.7/site-packages/numpy
Python version 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
nose version 1.3.7
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError

```

attached full file:
[03.python.txt](https://github.com/Homebrew/homebrew-python/files/543228/03.python.txt)

specifically:
ERROR: test_callback.TestF77Callback.test_string_callback

I've tried the "brew unlink numpy; brew link --overwrite numpy" trick to no avail...

thanks for any help.

**Comment by CubeVato** [comment]
Hmm, this happened to me on one machine but not the other. The error message is a little misleading. If you look at the log file, the real issue is the linker can't seem to find some libraries. In my case, it was -lSystem and -lm. It looks like these used to be symlinks. See if this works:

`$ sudo bash -c 'for x in libSystem.dylib libm.dylib; do ln -s /usr/lib/libSystem.B.dylib "/usr/local/lib/${x}"; done'`

**Comment by itsayellow** [comment]
Thanks for the help @CubeVato .  
I did the symlinks that you suggested to make a link to those two libraries appear in /usr/local/lib.  (Both seemed to be needed.)  That seemed to work.

The next question is why do we need to manually link some libraries? 

I think this may be some xcode weirdness in my system(s).  I had the full Xcode installed, and then at some point homebrew complained and asked me to install Xcode Command Line Tools on top of it, which I did.  There may be some confusion with my linked libraries due to competing xcode installations.

Interestingly, brew doctor has always said it thinks my system is fine.

As a side note, I just tried upgrading scipy and get the same problem about other linked libraries... :(

**Comment by itsayellow** [comment]
I tried fully installing all of my xcode and reinstalling xcode CLT, and I still get these libraries as missing.  scipy still fails to install with missing libraries too.

**Comment by itsayellow** [comment]
I did full `brew uninstall` of both numpy and scipy, and then reinstalled them.

This time they installed from bottles, so I didn't have to compile and it didn't complain.
This might be why nobody else has problems, they are just getting bottles and not having to compile them.

**Comment by CubeVato** [comment]
It looks like these symlinks used to be supplied by Apple but were removed at some point. The affected formulae probably just need to be updated to link against /usr/lib/libSystem.B.dylib. In the mean time, this same trick will probably work for SciPy, too. Can you post the log contents?

**Comment by itsayellow** [comment]
You're right, it's just libSystem that's the problem:
```
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
```
I removed the symlink to it from /usr/local/lib when I was trying to see if just updating xcode CLT would work (it didn't).

OK, so maybe it isn't an xcode issue.  I think my xcode pointer was pointing to my full Xcode installation instead of the CLT.  This seems to force homebrew to compile everything itself and not load bottles.

This seems like something that needs to be fixed in these homebrew recipes if Apple used to link to these libraries in /usr/local/lib but doesn't anymore.

**Comment by CubeVato** [comment]
Okay, I see what's going on. Numpy actually builds correctly, but then it tries to run the Numpy tests and fails. You can replicate it by installing Numpy (either from the bottle or from source), removing the symlinks (if present), and running `$ python -c "import numpy; numpy.test()"`

This is the first test that fails:
> /usr/local/bin/gfortran -Wall -g -Wall -g -undefined dynamic_lookup -bundle /var/folders/_d/0hg8gt656mngjstr2__cgr4m0000gn/T/tmpCHTpFn/var/folders/_d/0hg8gt656mngjstr2__cgr4m0000gn/T/tmpCHTpFn/src.macosx-10.12-x86_64-2.7/_test_ext_module_5403module.o /var/folders/_d/0hg8gt656mngjstr2__cgr4m0000gn/T/tmpCHTpFn/var/folders/_d/0hg8gt656mngjstr2__cgr4m0000gn/T/tmpCHTpFn/src.macosx-10.12-x86_64-2.7/fortranobject.o /var/folders/_d/0hg8gt656mngjstr2__cgr4m0000gn/T/tmpCHTpFn/var/folders/_d/0hg8gt656mngjstr2__cgr4m0000gn/T/tmpY2J8P7/tmpPSRiYk.o -L/usr/local/Cellar/gcc/6.2.0/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.2.0 -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -lgfortran -o ./_test_ext_module_5403.so

This invocation searches for libraries in /usr/local/lib (`-L/usr/local/lib`) but not /usr/lib, which is where libSystem.dylib lives. Since the symlinks aren't in /usr/local/lib anymore, the linker fails to find the library and the test fails.

**Comment by tdsmith** [comment]
Apple never created symlinks in /usr/local/lib. /usr/lib is in the default search path unless you have an Xcode-only installation, in which event the Xcode SDK folder should have a libsystem stub. I'm not sure I know what the issue is, yet.

**Comment by MikeMcQuaid** [comment]
This formula was moved to homebrew/core. Reopen there if you can still reproduce there, thanks.
