### ISSUE TITLE
Issues with brew install homebrew/python/pygame

### ISSUE THREAD

**Issue by dalisaydavid** [Homebrew/homebrew-python#361]
I run homebrew/python/pygame on my Mac and I receive errors with clang. I seen to always come back to this error:

==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/pygame/1.9.2a0 --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/daviddalisay/Library/Logs/Homebrew/pygame/02.python:
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:28: error: unknown type name 'NSArray'
@property (readonly, copy) NSArray<ObjectType> *allObjects;
                           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:35: error: expected member name or ';' after declaration specifiers
@property (readonly, copy) NSArray<ObjectType> *allObjects;
                           ~~~~~~~^
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:1: error: property requires fields to be named
@property (readonly, copy) NSArray<ObjectType> *allObjects;
^                          ~~~~~~~
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:35: error: expected ';' at end of declaration list
@property (readonly, copy) NSArray<ObjectType> *allObjects;
                                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
error: command 'clang' failed with exit status 1
--- 

Anyone have any ideas?

**Comment by tdsmith** [comment]
Please take a look at the troubleshooting guide in the URL displayed with the error message and provide the gist-logs link, thanks.
