### ISSUE TITLE
Need simbody bottles for El Capitan and Sierra.

### ISSUE THREAD

**Issue by lloydc99** [Homebrew/homebrew-python#372]
Builds on Travis CI will timeout on simbody because it takes longer than 10 minutes.
Bottles should fix that problem.

I built two bottles and placed them here.

https://www.dropbox.com/sh/xc6vyuthg6b4lo5/AAB2uXSaVLpvp1YlEsV6C8Gwa?dl=0

**Comment by MikeMcQuaid** [comment]
This formula was removed due to low usage. Please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) instead. Thanks![
