### ISSUE TITLE
upgrading pip3 breaks python2 environment

### ISSUE THREAD

**Issue by darkn3rd** [Homebrew/homebrew-python#378]
#### SUMMARY

Installed python and python3, now pip only installs python3 packages. 

#### STEPS

Installed python and updated pip as per instructions with `brew info python` and `brew info python3`

```
brew install python
pip install --upgrade pip setuptools
brew install python3
pip3 install --upgrade pip setuptools wheel
```

#### EXPECTED RESULTS

pip would install python 2 modules.

#### ACTUAL RESULTS

```
$ pip --version
pip 9.0.1 from /usr/local/lib/python3.5/site-packages (python 3.5)
$ pip2 --version
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
````

**Comment by MikeMcQuaid** [comment]
Unclear how this relates to this tap, sorry.
