### ISSUE TITLE
Vim unable to load Python's site module after 2.7.13 update

### ISSUE THREAD

**Issue by dorapen** [Homebrew/homebrew-python#379]
I just updated my Python to 2.7.13, and I'm using latest Homebrew Vim (8.0.134). After this update, whenever I try to launch vim it throws the following error:
`Error detected while processing function <SNR>36_InitializePythonBuiltin:
line   23:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.`

Same error is displayed when I try `:py print 'test'`

Does anyone know how to resolve this issue? Reinstalling both Python and Vim didn't help - but if I use system's Vim, then it works without the issue.

**Comment by ilovezfs** [comment]
please try rebuilding vim
```
brew reinstall -s vim
```

**Comment by dorapen** [comment]
@ilovezfs Sweet, that worked! Good to know about the sandbox mode as well :) Thanks a lot!

**Comment by ilovezfs** [comment]
@dorapen `-s` is a shortcut for `--build-from-source`. The sandbox is on during builds of things in homebrew/core by default. If you want to enable the sandbox when building something outside of core, you can force it to be used by passing `--sandbox` or by setting
```
export HOMEBREW_SANDBOX=1
```

**Comment by dorapen** [comment]
@ilovezfs Oh I see, when I ran that command brew was saying `Using the sandbox` so I thought that was sandbox mode. Thanks for your tip!

**Comment by ilovezfs** [comment]
@dorapen you're welcome!
