### ISSUE TITLE
Please provide `sqlparse` package

### ISSUE THREAD

**Issue by twang2218** [Homebrew/homebrew-python#383]
`pip install sqlparse` provides `sqlformat` command, and currently `brew install sqlformat` will installed the unmaintained php version of it. Could you provide `sqlparse` to have a real usable `sqlformat` command? And `sqlparse` is also used in Atom-Beautify plugin for beautify the SQL formatter.

**Comment by ilovezfs** [comment]
@twang2218 https://github.com/Homebrew/homebrew-core/pull/8679.

**Comment by twang2218** [comment]
@ilovezfs Great, thank you very much. 😸

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/8679.
